[build]
builder = "nixpacks"
buildCommand = """
apt-get update && apt-get install -y python3 python3-pip \
&& cd client_backend && pip3 install -r requirements.txt
"""

[deploy]
startCommand = "cd client_backend && python3 app.py"
healthcheckPath = "/"
healthcheckTimeout = 100

[service]
port = 5000