[build]
builder = "nixpacks"
buildCommand = """
apt-get update && apt-get install -y python3 python3-pip \
  libgl1 libsm6 libxext6 libxrender1 \
&& cd client_backend && pip3 install -r requirements.txt
"""

[deploy]
startCommand = "cd client_backend && gunicorn app:app --bind 0.0.0.0:5000"
healthcheckPath = "/"
healthcheckTimeout = 100

[service]
port = 5000